language: node_js
node_js:
  - stable
  - 10
cache:
  directories:
    - "node_modules"
before_deploy:
  - npm run build
  - npm run publish:npm
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    file:
      - './lib/index.js'
      - './package.json'
    on:
      tags: true
  - provider: pages
    local_dir: './build'
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: smshen17@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
